### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by RecordingTheSmile** [Jimmy-BL/Srr-WinForm-Edition#1]
开发者的开发经验可能少了一些，软件整体使用无大问题，但是有一些小问题需要修正。

比如Form1.cs的第163-167行:
```csharp
if (File.ReadAllText(NextFile.FullName) == "")
                        {
                            File.Delete(NextFile.FullName);
                            MessageBox.Show("发现空文件——" + NextFile.Name + "\n，已将其删除。", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        }
```

这里很明显，弹窗只是提示一下用户，用户的操作对于程序运行结果没有任何帮助，并且使用MessageBox.Show会阻塞整个线程的运行，也就是用户不关闭模态对话框，后面的代码是停止的不往后执行，但是主程序仍然会响应其他消息，比如Timer事件，造成时序逻辑混乱。
建议这类不影响程序运行结果的通知专门新建一个通知栏，以运行日志的方式呈现即可。另外模态对话框用的太多也可能影响程序整体运行对用户的友好度，建议慎用。

**Comment by Henry217** [comment]
> 开发者的开发经验可能少了一些，软件整体使用无大问题，但是有一些小问题需要修正。
> 
> 比如Form1.cs的第163-167行:
> 
> ```cs
> if (File.ReadAllText(NextFile.FullName) == "")
>                         {
>                             File.Delete(NextFile.FullName);
>                             MessageBox.Show("发现空文件——" + NextFile.Name + "\n，已将其删除。", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
>                         }
> ```
> 
> 这里很明显，弹窗只是提示一下用户，用户的操作对于程序运行结果没有任何帮助，并且使用MessageBox.Show会阻塞整个线程的运行，也就是用户不关闭模态对话框，后面的代码是停止的不往后执行，但是主程序仍然会响应其他消息，比如Timer事件，造成时序逻辑混乱。
> 建议这类不影响程序运行结果的通知专门新建一个通知栏，以运行日志的方式呈现即可。另外模态对话框用的太多也可能影响程序整体运行对用户的友好度，建议慎用。

其实这个很好解决

通过通知中心通知就行

单独辟一块日志栏，其实也没人会看，反而影响了整体的美感

**Comment by Jimmy-BL** [comment]
> 
> 
> > 开发者的开发经验可能少了一些，软件整体使用无大问题，但是有一些小问题需要修正。
> > 比如Form1.cs的第163-167行:
> > ```cs
> > if (File.ReadAllText(NextFile.FullName) == "")
> >                         {
> >                             File.Delete(NextFile.FullName);
> >                             MessageBox.Show("发现空文件——" + NextFile.Name + "\n，已将其删除。", "Info", MessageBoxButtons.OK, MessageBoxIcon.Information);
> >                         }
> > ```
> > 
> > 
> > 这里很明显，弹窗只是提示一下用户，用户的操作对于程序运行结果没有任何帮助，并且使用MessageBox.Show会阻塞整个线程的运行，也就是用户不关闭模态对话框，后面的代码是停止的不往后执行，但是主程序仍然会响应其他消息，比如Timer事件，造成时序逻辑混乱。
> > 建议这类不影响程序运行结果的通知专门新建一个通知栏，以运行日志的方式呈现即可。另外模态对话框用的太多也可能影响程序整体运行对用户的友好度，建议慎用。
> 
> 其实这个很好解决
> 
> 通过通知中心通知就行
> 
> 单独辟一块日志栏，其实也没人会看，反而影响了整体的美感

日志栏是给他们复制和更长时间看用的，你可以在优化优化，我现在这个电脑是Win8，用不了VS

你再把你那个有通知中心的程序和源码发给我一下,发到我的邮箱里去，我来给你弄一个版本号，我那个ＱＱ被冻结了，可能要到暑假。

**Comment by Jimmy-BL** [comment]
这个问题已经在Henry217发布的另一个版本中，我正在等待他的那个版本。

在收到该版本之前，我将先将该问题关闭。

该问题将在暑假得到彻底性的解决。另外在暑假将会推出全新版本。
